import { PL, RU } from "../constants/languageCodes";

import { PizzaMenu, PizzaMenuOptions } from "../types/common";

export const pizzaMenuPl: Array<PizzaMenuOptions> = [
  {
    id: "1",
    name: "Margherita",
    ingridients: ["sos", "pomidorowy", "mozzarella", "oregano"],
    image: "",
  },
  {
    id: "2",
    name: "Z pieczarkami",
    ingridients: ["sos", "pomidorowy", "mozzarella", "pieczarki", "oregano"],
    image: "",
  },
  {
    id: "3",
    name: "Zablakana Kula",
    ingridients: [
      "sos",
      "pomidorowy",
      "mozzarella",
      "papryczka",
      "pieczarki",
      "bekon",
      "czerwona",
      "cebula",
      "oliwki",
      "oregano",
    ],
    image: "",
  },
  {
    id: "4",
    name: "Ze szpinakiem",
    ingridients: [
      "sos",
      "pomidorowy",
      "mozzarella",
      "szpinak",
      "pomidory",
      "koktailowe",
      "ser",
      "rikotta",
      "oregano",
    ],
    image: "",
  },
  {
    id: "5",
    name: "Wegeteriana",
    ingridients: [
      "sos",
      "pomidorowy",
      "mozzarella",
      "pieczarki",
      "papryka",
      "slodka",
      "cebula",
      "czerwona",
      "pomidor",
      "oregano",
    ],
    image: "",
  },
  {
    id: "6",
    name: "Gorgonzolą",
    ingridients: [
      "sos",
      "pomidorowy",
      "mozzarella",
      "pomidor",
      "cherry",
      "gorgonzola",
      "oliwki",
      "czarne",
      "oregano",
    ],
    image: "",
  },
  {
    id: "7",
    name: "Die osie",
    ingridients: [
      "sos",
      "pomidorowy",
      "mozzarella",
      "kurczak",
      "ananas",
      "kielbasa",
      "chorizo",
      "oliwki",
      "oregano",
    ],
    image: "",
  },
  {
    id: "8",
    name: "Bandycka",
    ingridients: [
      "sos",
      "pomidorowy",
      "mozzarella",
      "pancetta",
      "pomidor",
      "jalapeno",
      "czerwona",
      "cebula",
      "oregano",
    ],
    image: "",
  },
  {
    id: "9",
    name: "Salami",
    ingridients: [
      "sos",
      "pomidorowy",
      "mozzarella",
      "salami",
      "pieczarki",
      "oliwki",
      "oregano",
    ],
    image: "",
  },
  {
    id: "10",
    name: "Cztery Sery",
    ingridients: [
      "sos",
      "pomidorowy",
      "mozzarella",
      "gorgonzola",
      "ricotta",
      "grana padano",
      "szpinak",
      "oregano",
    ],
    image: "",
  },
  {
    id: "11",
    name: "Hawajska",
    ingridients: [
      "sos",
      "pomidorowy",
      "mozzarella",
      "szynka",
      "ananas",
      "oregano",
    ],
    image: "",
  },
  {
    id: "12",
    name: "Cztery Kule",
    ingridients: [
      "sos",
      "pomidorowy",
      "mozzarella",
      "kabanos",
      "szynka",
      "czerwona cebula",
      "ogórek konserwowy",
      "oregano",
    ],
    image: "",
  },
  {
    id: "13",
    name: "Wendeta",
    ingridients: [
      "sos",
      "pomidorowy",
      "mozzarella",
      "kurczak",
      "kabanos",
      "biala cebula",
      "jalapeno",
      "oregano",
    ],
    image: "",
  },
  {
    id: "14",
    name: "Krakowska",
    ingridients: [
      "sos",
      "pomidorowy",
      "mozzarella",
      "kielbasa krakowska",
      "pieczarki",
      "ogorek konserwowy",
      "ser burrata",
      "oregano",
    ],
    image: "",
  },
  {
    id: "15",
    name: "Prosciutto",
    ingridients: [
      "sos",
      "pomidorowy",
      "mozzarella",
      "szynka parmeńska",
      "rukola",
      "oliwki",
      "ser garana padano oregano",
    ],
    image: "",
  },
  {
    id: "16",
    name: "Diablo",
    ingridients: [
      "sos",
      "pomidorowy",
      "mozzarella",
      "czerwona papryka",
      "oliwa",
      "rukola",
      "oregano",
    ],
    image: "",
  },
  {
    id: "17",
    name: "Hamilton",
    ingridients: [
      "sos",
      "pomidorowy",
      "mozzarella",
      "salami",
      "czerwona cebula",
      "pomidor cherry",
      "oliwki",
      "oregano",
    ],
    image: "",
  },
  {
    id: "18",
    name: "Pizza Bonnie & Clude",
    ingridients: [
      "sos",
      "pomidorowy",
      "mozzarella",
      "kurczak",
      "pancetta",
      "pieczarki",
      "oliwki czarne",
      "ser grana padano",
      "oregano",
    ],
    image: "",
  },
  {
    id: "19",
    name: "Tomsan",
    ingridients: [
      "sos",
      "pomidorowy",
      "mozzarella",
      "szynka",
      "pieczarki",
      "kukurydza",
      "czerwona cebula",
      "oregano",
    ],
    image: "",
  },
  {
    id: "20",
    name: "Rewolwer",
    ingridients: [
      "sos",
      "pomidorowy",
      "mozzarella",
      "boczek",
      "salami",
      "pieczarki",
      "czosnek",
      "oregano",
    ],
    image: "",
  },
  {
    id: "21",
    name: "Zly Clyde",
    ingridients: [
      "sos",
      "pomidorowy",
      "mozzarella",
      "salami",
      "chorizo",
      "jalapeno",
      "chilli",
      "oregano",
    ],
    image: "",
  },
  {
    id: "22",
    name: "Z krewetkami",
    ingridients: [
      "sos",
      "pomidorowy",
      "mozzarella",
      "krewetki",
      "papryka slodka",
      "oliwki",
      "burrata",
      "oregano",
    ],
    image: "",
  },
  {
    id: "23",
    name: "Soczysta Bonnie",
    ingridients: [
      "sos",
      "pomidorowy",
      "mozzarella",
      "czerwona cebula",
      "bekon",
      "burrata",
      "pesto basilico",
      "pomidor cherry",
      "aregano",
    ],
    image: "",
  },
  {
    id: "24",
    name: "Mysliwska",
    ingridients: [
      "sos",
      "pomidorowy",
      "mozzarella",
      "boczek",
      "szynka",
      "kielbasa krakowska",
      "kabanos",
      "biala cebula",
      "pomidor",
    ],
    image: "",
  },
];

export const pizzaMenuRu: Array<PizzaMenuOptions> = [
  {
    id: "1",
    name: "Margherita",
    ingridients: ["томатный  соус", "моцарелла", "орегано"],
    image: "",
  },
  {
    id: "2",
    name: "Z pieczarkami",
    ingridients: ["томатный  соус", "моцарелла", "грибы", "орегано"],
    image: "",
  },
  {
    id: "3",
    name: "Zabląkana Kyla",
    ingridients: [
      "томатный  соус",
      "моцарелла",
      "перец",
      "грибы",
      "бекон",
      "красный лук",
      "оливки",
      "орегано",
    ],
    image: "",
  },
  {
    id: "4",
    name: "Ze szpinakiem",
    ingridients: [
      "томатный  соус",
      "моцарелла",
      "шпинат",
      "помидор черри",
      "сыр рикотта",
      "орегано",
    ],
    image: "",
  },
  {
    id: "5",
    name: "Wegeteriana",
    ingridients: [
      "томатный  соус",
      "моцарелла",
      "грибы",
      "сладкий перец",
      "красный лук",
      "помидор",
      "орегано",
    ],
    image: "",
  },
  {
    id: "6",
    name: "Gorgonzola",
    ingridients: [
      "томатный  соус",
      "моцарелла",
      "помидор черри",
      "горгонзола",
      "черные оливки",
      "орегано",
    ],
    image: "",
  },
  {
    id: "7",
    name: "Dwie Osie",
    ingridients: [
      "томатный  соус",
      "моцарелла",
      "курица",
      "ананас",
      "колбаса",
      "оливки",
      "орегано",
    ],
    image: "",
  },
  {
    id: "8",
    name: "Bandycka",
    ingridients: [
      "томатный  соус",
      "моцарелла",
      "панчетта",
      "помидор",
      "халапеньо",
      "красный лук",
      "орегано",
    ],
    image: "",
  },
  {
    id: "9",
    name: "Salame",
    ingridients: [
      "томатный  соус",
      "моцарелла",
      "салями",
      "грибы",
      "оливки",
      "орегано",
    ],
    image: "",
  },
  {
    id: "10",
    name: "Cztery Sery",
    ingridients: [
      "томатный  соус",
      "моцарелла",
      "горгонзола",
      "рикотта",
      "грана падано",
      "шпинат",
      "орегано",
    ],
    image: "",
  },
  {
    id: "11",
    name: "Hawajska",
    ingridients: [
      "томатный  соус",
      "моцарелла",
      "ветчина",
      "ананас",
      "орегано",
    ],
    image: "",
  },
  {
    id: "12",
    name: "Cztery Kule",
    ingridients: [
      "томатный  соус",
      "моцарелла",
      "кабанос",
      "ветчина",
      "красный лук",
      "маринованный огурец",
      "орегано",
    ],
    image: "",
  },
  {
    id: "13",
    name: "Wendeta",
    ingridients: [
      "томатный  соус",
      "моцарелла",
      "курица",
      "кабаноc",
      "белый лук",
      "халапеньо",
      "орегано",
    ],
    image: "",
  },
  {
    id: "14",
    name: "Krakowska",
    ingridients: [
      "томатный  соус",
      "моцарелла",
      "краковская колбаса",
      "грибы",
      "огурец",
      "сыр буррата",
      "орегано",
    ],
    image: "",
  },
  {
    id: "15",
    name: "Prosciutto",
    ingridients: [
      "томатный  соус",
      "моцарелла",
      "ветчина",
      "руккола",
      "оливки",
      "орегано",
      "сыр",
    ],
    image: "",
  },
  {
    id: "16",
    name: "Diablo",
    ingridients: [
      "томатный  соус",
      "моцарелла",
      "салями",
      "грибы",
      "красный перец",
      "оливковое масло",
      "руккола",
      "орегано",
    ],
    image: "",
  },
  {
    id: "17",
    name: "Hamilton",
    ingridients: [
      "томатный  соус",
      "моцарелла",
      "салями",
      "красный лук",
      "помидор черри",
      "оливки",
      "орегано",
    ],
    image: "",
  },
  {
    id: "18",
    name: "Pizza Bonnie & Clude",
    ingridients: [
      "томатный  соус",
      "моцарелла",
      "курица",
      "панчетта",
      "грибы",
      "черные оливки",
      "грана сыр падано",
      "орегано",
    ],
    image: "",
  },
  {
    id: "19",
    name: "Tomsan",
    ingridients: [
      "томатный  соус",
      "моцарелла",
      "ветчина",
      "грибы",
      "кукуруза",
      "красный лук",
      "орегано",
    ],
    image: "",
  },
  {
    id: "20",
    name: "Rewolwer",
    ingridients: [
      "томатный  соус",
      "моцарелла",
      "бекон",
      "салями",
      "грибы",
      "чеснок",
      "орегано",
    ],
    image: "",
  },
  {
    id: "21",
    name: "Zły Clyde",
    ingridients: [
      "томатный  соус",
      "моцарелла",
      "салями",
      "чоризо",
      "халапеньо",
      "чили",
      "орегано",
    ],
    image: "",
  },
  {
    id: "22",
    name: "Z krewetkami",
    ingridients: [
      "томатный  соус",
      "моцарелла",
      "креветки",
      "сладкий перец",
      "оливки",
      "буррата",
      "орегано",
    ],
    image: "",
  },
  {
    id: "23",
    name: "Soczysta Bonnie",
    ingridients: [
      "томатный  соус",
      "моцарелла",
      "красный лук",
      "бекон",
      "буррата",
      "базилико песто",
      "помидор черри",
      "oрегано",
    ],
    image: "",
  },
  {
    id: "24",
    name: "Myśliwska",
    ingridients: [
      "томатный  соус",
      "моцарелла",
      "бекон",
      "колбаса краковская",
      "кабаноc",
      "белый лук",
      "помидоры",
    ],
    image: "",
  },
];

export const pizzaMenu: PizzaMenu = {
  [PL]: pizzaMenuPl,
  [RU]: pizzaMenuRu,
};
